apiVersion: v1
kind: ConfigMap
metadata:
  name: django-env
  namespace: default
data:
  S3_ENDPOINT_URL: "http://10.21.51.41:7200/"
  STATIC_BUCKET: "oscarstatic-xxx"
  DATABASE_NAME: "oscar_django_xxx"
