apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  labels:
    app: django
    component: db
    tier: backend
type: Opaque
data:
  user: cG9zdGdyZXM=
  password: VGhpc0lzQVZlcnlMb25nQW5kU3Ryb25nUGFzc3dvcmRPSw==
