apiVersion: v1
kind: Secret
metadata:
  name: object-credentials
  labels:
    app: django
    component: storage
    tier: backend
type: Opaque
data:
  access: cG9zZWlkb25fYWNjZXNz
  secret: cG9zZWlkb25fc2VjcmV0
